<table class="table table-dark">
	<?php $users = $block->getUserList(); ?>
	<thead>
		<tr>
			<?php
			foreach ($users as $key => $value) {
				echo "<td>{$key}</td>";
			}
			?>
		</tr>
	</thead>
	<tbody>
		<tr>
			<?php
			$numArray = array_values($users);
			for ($row = 0; $row < count($numArray[0]); $row++) {
				echo "<tr>";
				for ($i = 0; $i < count($numArray); $i++) {
					echo "<td>{$numArray[$i][$row]}</td>";
				}
				echo "</tr>";
			}
			?>
		</tr>
	</tbody>
</table>
<?php
	print "<pre>";
	print_r($numArray);
	print "</pre>";
?>